apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: javaee-cafe
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      name: javaee-cafe
      labels:
        app: javaee-cafe
    spec:
      containers:
      - name: javaee-cafe
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
        image: rezarahman/javaee-cafe:v1
---
apiVersion: v1
kind: Service
metadata:
  name: javaee-cafe
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9080
  selector:
    app: javaee-cafe
