pipeline {
	//agent {
	//	docker {
	//		image 'maven:3-alpine'
	//		args '-v /root/.m2:/root/.m2'
	//	}
	//}
	def mvnHome = tool 'maven_3_5_4'

	stages {
		stage ('Build') {

			steps {
				//withMaven(maven : 'maven_3_5_4'){
					sh '${mvnHome}/bin/mvn -Dmaven.test.failure.ignore clean package'
				//}
			}
		}

		stage ('Deploy') {

			steps {
				//withMaven(maven : 'maven_3_5_4') {
					sh '${mvnHome}/bin/mvn -Dmaven.test.failure.ignore  deploy'
				//}
			}
		}
	}
}