pipeline {
	agent {
		docker {
			image 'maven:3-alpine'
			args '-v /root/.m2:/root/.m2'
		}
	}

	stages {
		stage ('Build') {

			steps {
				//withMaven(maven : 'maven_3_5_4'){
					sh 'mvn clean package'
				//}
			}
		}

		stage ('Deploy') {

			steps {
				//withMaven(maven : 'maven_3_5_4') {
					sh 'mvn deploy'
				//}
			}
		}
	}
}